### ISSUE TITLE
funciona?

### ISSUE THREAD

**Issue by vonpupp** [rubencabrera/bitcoin_payments#1]
Hola Ruben,

Funciona tu modulo?

Gracias y saludos.

**Comment by rubencabrera** [comment]
Hola, @vonpupp, perdona por la tardanza, se me había pasado la notificación.

Este módulo lo utilizamos hace tiempo para probar el concepto, pero el cliente dejó de tener interés en ello y no se ha puesto nunca en producción. 

Te recomiendo que pruebes y hagas algo de ruido en el PR siguiente:
https://github.com/OCA/account-payment/pull/96

También hay algunas funcionalidades útiles en:
https://github.com/OCA/account-financial-tools/pull/480

Puedes hacerme ping en esos PR's y estaré encantado de ayudar a que salgan adelante.

**Comment by rubencabrera** [comment]
Cierro el issue, pero no por falta de interés, sino por no tener este repo coleando. De hecho, cuando me acuses recibo creo que lo mejor será que borre el repositorio y no haga perder el tiempo a nadie más que esté buscando la funcionalidad que éste módulo no cubre.

**Comment by vonpupp** [comment]
Vale gracias Ruben, le echare un ojo.

Talvez sea mejor colocar un readme y explicar que esta deprecated y que continua alli por si a alguien le pudiese ser util para continuar el desarrollo (si fuese el caso). Como tu lo veas mejor.
